CREATE SEQUENCE SQ_CLIENTE NO minvalue NO MAXVALUE;
CREATE TABLE loteria.CLIENTE (
	ID_CLIENTE int8 NOT NULL,
	TX_EMAIL varchar(255) NOT null,
	
	CONSTRAINT pk_CLIENTE PRIMARY KEY (ID_CLIENTE)
);


CREATE SEQUENCE SQ_APOSTA NO minvalue NO MAXVALUE;
CREATE TABLE loteria.APOSTA ( 
	ID_APOSTA int8 NOT NULL,
	NUMERO int8 NOT NULL,
	DT_APOSTA timestamp NOT NULL,
	ID_CLIENTE int8 NOT NULL,
	
	CONSTRAINT pk_APOSTA PRIMARY KEY (ID_APOSTA),
	CONSTRAINT fk_APOSTA FOREIGN KEY (ID_CLIENTE) REFERENCES loteria.CLIENTE(ID_CLIENTE)
);
